### ISSUE TITLE
Isn't this already a thing...?

### ISSUE THREAD

**Issue by MoDerPo** [xmile1/reopenclosedtab#6]
you can just press `ctrl`+`shift`+`tab`

**Comment by ashuvssut** [comment]
I disagree @MoDerPo 

I think pressing `ctrl+shift+tab`  switches between opened editors.
Its not for reopening last closed editors.

`ctrl+shift+t` is a keyboard shortcut to reopen last closed editors.

this extension is not needed because, this is a in-built VS Code feature now!

**Comment by MoDerPo** [comment]
Oh you're right, I wrote `tab` but meant `t`lol
